# Generated by Django 3.2.6 on 2021-08-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qustno', models.CharField(max_length=300)),
                ('Qustn', models.CharField(max_length=200)),
                ('OptA', models.CharField(max_length=200)),
                ('optB', models.CharField(max_length=200)),
                ('OptC', models.CharField(max_length=200)),
                ('OptD', models.CharField(max_length=200)),
                ('RightAns', models.IntegerField()),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
