# Generated by Django 3.2.6 on 2021-08-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=300)),
                ('opta', models.CharField(max_length=50)),
                ('optb', models.CharField(max_length=50)),
                ('optc', models.CharField(max_length=50)),
                ('optd', models.CharField(max_length=50)),
            ],
        ),
    ]
