# Generated by Django 3.2.6 on 2021-08-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountno', models.CharField(max_length=300)),
                ('accountname', models.CharField(max_length=50)),
                ('accountid', models.CharField(max_length=50)),
                ('accounttype', models.CharField(max_length=50)),
                ('accountbalance', models.CharField(max_length=50)),
            ],
        ),
    ]
